### ISSUE TITLE
TODO  -List of Carpentries instructors in Norway 

### ISSUE THREAD

**Issue by vivigirardin** [uio-carpentry/governance#1]
We should have a list of "Active" and "Inactive" instructors to value those who actually do the job. I am not sure if it is possible to exclude from the list those who never taught a single course, but my suggestion is to only add the name of instructors who have taught a certain number of courses to the list. Helpers and co-instructors should also be added to the list.

**Comment by annefou** [comment]
We could also (in addition) list names of instructors for workshops.

**Comment by naoe-tatara** [comment]
Now [Carpentries Nordic Region page](https://carpentries.org/regions_nordic/) shows a list of instructors with country flag. In Autumn 2019, a survey was carried out to gather information of instructors who are willing to teach. The survey result is not publicly open, but presented in an interim board meeting in late 2019. I don't quite understand if this issue is still needing more action, but if so, it will be nice if a clearer task is given :)

**Comment by lexnederbragt** [comment]
I think the task is to find a way to internally log active Carpentry@UiO instructors and past/paused/otherwise inactive ones. Maybe a google doc somewhere, that gets updated in January and August by asking all instructors again?

**Comment by lexnederbragt** [comment]
There is a TODO in the intro.rst file/text about this. We need to decide whether we are going to ask permission to publish Carpentry@UiO instructor's names on this page (or elsewhere) or whether we don't want to do that.

**Comment by arockenberger** [comment]
Naoe and I have worked on this when we did the mailing list updates. we will inform about this at the next board meeting.

**Comment by Teebusch** [comment]
I found this "TODO" in the governance docs, after the board member list:

```
Give a list of Carpentries instructors in Norway :
- can be taken from <https://github.com/carpentries/carpentries.org/blob/gh-pages/_data/publish_instructors.csv>
-  does not differentiate Oslo from other cities (NORWAY only)
Here we should make sure we acknowledge member participation one way or another. 
```

The linked dataset does not exist anymore. There is one in that repo that has instructors by airport, but it only has initials for the names, and it is not complete ("TB" is missing 😅)

```
  {
    "airport_code": "OSL",
    "airport_latitude": 60.193889,
    "airport_longitude": 11.100278,
    "instructors": [
      "MB",
      "ACC",
      "HF",
      "AF",
      "MH",
      "KL",
      "LN",
      "AO",
      "TMDP",
      "AR"
    ]
  },
```

**Comment by naoe-tatara** [comment]
Thanks @Teebusch for pointing out this and following up! My understanding is that I will take contact to 

1. those in org list
2. not 1 but taught/helped at UiO Carpentry workshops

if it is OK to list their name as either

1. current contributor/member (if certified instructor/trainer, under that category as well)
2. alumni

on 

1. Both INTRO page under ub.uio.no/ (in the accordion menu) and uio-carpentry.github.io 
2. Only INTRO page
3. Only uio-carpentry.github.io page 

Or not agree to be listed.

So the cited information here is outdated. 

I was planning to send an inquiry, but while I was overloaded with other tasks, it became more or less holiday seasons, and thought it would be better to wait until January. But maybe it is OK to send it anyways and add names accordingly when they arrive?

**Comment by lexnederbragt** [comment]
Closing as this is now addressed at https://www.ub.uio.no/english/writing-publishing/dsc/carpentry-uio/index.html

**Comment by lexnederbragt** [comment]
and at https://github.com/uio-carpentry/uio-carpentry.github.io/pull/33
