### ISSUE TITLE
List of board members

### ISSUE THREAD

**Issue by naoe-tatara** [uio-carpentry/governance#12]
Are we going to elect officers first before publishing who are board members or are we first publishing board member names in alphabetical order or any other more preferable order?

Also do we all agree on publishing our name? I agree.

**Comment by Teebusch** [comment]
I also agree. I'd say we can puvblish the names now and add the "offices" to the list later.

**Comment by vivigirardin** [comment]
I also agree

**Comment by arockenberger** [comment]
I agree. We can publish the officer roles once we have decided who wants to do what. :)

**Comment by lexnederbragt** [comment]
I agree on my name being mentioned and publishing names before roles are decided. Please also ask the interring board whether they are OK to be named (for posterity).

**Comment by annesbe** [comment]
I agree, and I am fine with names being published.

**Comment by arockenberger** [comment]
Updated and merged!
