### ISSUE TITLE
organisation -> 'club'

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/governance#13]
From the minutes of the [200325 board meeting](https://github.com/uio-carpentry/organisational/blob/master/meetings/200325-board-meeting.md): Carpentry@UiO is not registered as an official organization. It is more like a "club".

**Comment by arockenberger** [comment]
What kind of action should be taken here? Can someone create a pull-request?

**Comment by lexnederbragt** [comment]
Won't fix here
