### ISSUE TITLE
Describe the tasks/roles/responsibilities of the board

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/governance#14]
During the [200325 board meeting](https://github.com/uio-carpentry/organisational/blob/master/meetings/200325-board-meeting.md) it became clear that this description is needed.

**Comment by lexnederbragt** [comment]
See https://docs.google.com/document/d/1109uUcCBiu_HUkE8f1CMVzUU3sHX4p0NbK4F9bt-z4w/edit?usp=sharing

**Comment by lexnederbragt** [comment]
Google doc updated based on comments during the 200506 board meeting. Please review [the current text](https://docs.google.com/document/d/1109uUcCBiu_HUkE8f1CMVzUU3sHX4p0NbK4F9bt-z4w/edit?usp=sharing).

**Comment by arockenberger** [comment]
Should go on agenda for next board meeting!

**Comment by lexnederbragt** [comment]
Agreed

**Comment by lexnederbragt** [comment]
Migrating to https://github.com/uio-carpentry/organisational/issues/90
