### ISSUE TITLE
Migrate content to new website and archive this repo

### ISSUE THREAD

**Issue by Teebusch** [uio-carpentry/governance#27]
there are only 2 relatively short documents being maintained here. I suggest to maintain these directly on the new website and archive this repo. 

- Perhaps. the 'readthedocs' site should be officially archived, too.
- Transfer important issues to the website repo, if needed

**Comment by lexnederbragt** [comment]
Agreed

**Comment by Teebusch** [comment]
Shall we move forward on this? The new website is up, and the governance documents will be maintained there from now on.

**Comment by lexnederbragt** [comment]
I'd like to ask @annefou for her opinion, as she started the work on this repo and website. Anne, we have merged a few things into the new https://uio-carpentry.github.io website including the information in this repository. Are you OK with archiving this repo?

**Comment by annefou** [comment]
Of course!

**Comment by lexnederbragt** [comment]
Thanks!

**Comment by lexnederbragt** [comment]
New action point: adjust content to point to the new website

- [ ] README.md
- [ ] index.rst
- [ ] charter.rst

**Comment by Teebusch** [comment]
Closed by PR #28, I believe.

**Comment by lexnederbragt** [comment]
I made a new attempt in #29.

**Comment by lexnederbragt** [comment]
PR merged. Transfer process complete. Closing this issue and archiving the repository.
