### ISSUE TITLE
Code of Conduct Violation

### ISSUE THREAD

**Issue by annefou** [uio-carpentry/governance#3]
Update Chart for Code of Conduct violation (with inputs from Live).

**Comment by naoe-tatara** [comment]
If I understand correctly, as long as workshops etc. at UiO are labeled with Carpentries (inc. those teaching SWC/DC partially), any violation of CoC should be reported to Carpentries central. The workshop website also has a link to reporting form, which I found, for some reason, the new template may have a bug that a link is not properly implemented in the workshop website (at least links are broken on most of the recent Carpentries workshops websites at UiO). What should be covered by Carpentry@UiO in this regard?

**Comment by lexnederbragt** [comment]
If a violation happens outside of official Carpentry's workshops, I think the best we can do is to suggest using UiO's [speak-up](https://www.uio.no/english/about/hse/speak-up/index.html) or [si-fra](https://www.uio.no/om/hms/si-fra/) reporting.
