### ISSUE TITLE
Do not make workshop sign up pulbic

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/governance#4]

**Comment by lexnederbragt** [comment]
https://carpentry-uio-docs.readthedocs.io/en/latest/intro.html#contributing: The site should probably not link to the google sheet where we organise workshop, but have som text 'contact us' instead.

**Comment by naoe-tatara** [comment]
I agree. This link and probably the sentence should be changed to something like;
"If you wish to teach or help at upcoming workshops, please reply to the call sent to organizers @ swcarpentry dot uio dot no mailing list or contact carpadmin @ swcarpentry dot uio dot no. For more information, please refer to [Carpentry@UiO onboarding checklist](https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/onboarding-checklist.md#how-do-i-get-started-with-teaching-a-carpentries-workshop-at-uio)"

**Comment by naoe-tatara** [comment]
Sorry, I misunderstood and pressed "close and comment"!

**Comment by lexnederbragt** [comment]
Your proposed solution is very good. Could you submit a PR to that effect?

**Comment by lexnederbragt** [comment]
I went ahead and am preparing a PR now.

**Comment by naoe-tatara** [comment]
Thank you, Lex, and sorry for being behind!
