### ISSUE TITLE
carpentry@uio automatically becomes a mailto:link in html

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/governance#9]
Example: https://github.com/uio-carpentry/governance/blob/master/intro.rst has several times `Carpentry@UiO` that are not hyperlinks in the raw text, but when rendered into html at https://governance.readthedocs.io/en/latest/intro.html. Solution: turn into links to https://www.uio.no/english/for-employees/support/research/research-data/training/carpentry/

**Comment by arockenberger** [comment]
Reviewed and merged pull requests #10 and #11
